---
- name: Run Postgres container
  community.docker.docker_container:
    name: postgres
    image: postgres:15
    state: started
    restart_policy: always
    env:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloakpass
      POSTGRES_DB: keycloak
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  vars:
    pg_data: /opt/pg_data